"""Remove beneficiary column from Transaction table

Revision ID: 7f58d5a616e5
Revises: ada145fb685a
Create Date: 2025-02-28 09:16:05.581794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f58d5a616e5'
down_revision = 'ada145fb685a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('beneficiary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficiary', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
