"""Change description to TransactionType enum

Revision ID: 9f6aa1833d31
Revises: 7f58d5a616e5
Create Date: 2025-02-28 09:50:42.862929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6aa1833d31'
down_revision = '7f58d5a616e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Enum('CARD_PAYMENT', 'TRANSACTION', 'ONLINE_TRANSFER', name='transactiontype'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Enum('CARD_PAYMENT', 'TRANSACTION', 'ONLINE_TRANSFER', name='transactiontype'),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
