"""Initial migration

Revision ID: ada145fb685a
Revises: dc6bf6a266aa
Create Date: 2025-02-27 18:33:54.584109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada145fb685a'
down_revision = 'dc6bf6a266aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SENT', 'RECEIVED', 'PAID', name='transactionstate'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.Enum('SENT', 'RECEIVED', 'PAID', name='transactionstate'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
