"""Remove balance column from Account model

Revision ID: de1360899e70
Revises: 9f6aa1833d31
Create Date: 2025-02-28 10:29:12.562416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1360899e70'
down_revision = '9f6aa1833d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.NUMERIC(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
